version: '3.1'

services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        ports:
            - 13306:3306
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./config/:/docker-entrypoint-initdb.d/

    baobab:
        build: .
        image: baobab
        container_name: baobab
        restart: always
        ports:
            - 8080:80
            - 7443:443
        depends_on:
            - db
        links:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./:/var/www/html/
            - ../../baobab_config:/var/baobab_config/
